### ISSUE TITLE
[REQUEST] - A small change to "Forgot licence key?"

### ISSUE THREAD

**Issue by rabbewow** [danny-tdf/project-pegasus#3]
Instead of `<a class="text-white-50" href="https://fantasy.cat/forums/index.php">Forgot your license key?</a>`

You could use `<a class="text-white-50" href="https://fantasy.cat/forums/index.php?forums/membership-applications.47/">Forgot your license key?</a>`, So it automatically goes to the Membership Applications page and you can just click on your own application and get the license key from there.

**Comment by danny-tdf** [comment]
~~Will implement in the next update~~

**Comment by danny-tdf** [comment]
EDIT: on second thought, the only reason that anchor exists is in case non-members try to use the menu. The forum doesn't always accept new membership applications so if that URL is used while the thread is hidden/private, it will throw an error 401 or 403 depending on how XenForo deals with permissions. So it is better to just send them to the index page of the forum. Or better yet to the main page since they are new members.

As for finding your license, IMO every member should be able to do that easily. That's how we all did it at first and that quick link will most likely not always be there to help you.
